//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAVO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class l2dataAVO5Entities : DbContext
    {
        public l2dataAVO5Entities()
            : base("name=l2dataAVO5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sv_Web_RollProdLine> sv_Web_RollProdLine { get; set; }
        public DbSet<sv_Web_TimeProduction> sv_Web_TimeProduction { get; set; }
    
        public virtual ObjectResult<sp_web_LoadDetalOTM_Result> sp_web_LoadDetalOTM(string localId, Nullable<int> numberOTM)
        {
            var localIdParameter = localId != null ?
                new ObjectParameter("LocalId", localId) :
                new ObjectParameter("LocalId", typeof(string));
    
            var numberOTMParameter = numberOTM.HasValue ?
                new ObjectParameter("NumberOTM", numberOTM) :
                new ObjectParameter("NumberOTM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_web_LoadDetalOTM_Result>("sp_web_LoadDetalOTM", localIdParameter, numberOTMParameter);
        }
    
        public virtual ObjectResult<sp_web_RollInStend_Result> sp_web_RollInStend(string stendNumber)
        {
            var stendNumberParameter = stendNumber != null ?
                new ObjectParameter("StendNumber", stendNumber) :
                new ObjectParameter("StendNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_web_RollInStend_Result>("sp_web_RollInStend", stendNumberParameter);
        }
    }
}
