//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAVO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagramToRollAVO
    {
        public string RollNumber { get; set; }
        public string StendNumber { get; set; }
        public string NInStend { get; set; }
        public System.DateTime UtcDateTime { get; set; }
        public Nullable<decimal> ln { get; set; }
        public Nullable<decimal> p_speed { get; set; }
        public Nullable<decimal> p_extract { get; set; }
        public Nullable<decimal> p_P1750 { get; set; }
        public Nullable<decimal> p_B800 { get; set; }
        public Nullable<decimal> p_ILH { get; set; }
        public Nullable<decimal> p_ILL { get; set; }
        public Nullable<decimal> p_IRH { get; set; }
        public Nullable<decimal> p_IRL { get; set; }
        public Nullable<decimal> p_texture { get; set; }
        public Nullable<decimal> p_TLH { get; set; }
        public Nullable<decimal> p_TLL { get; set; }
        public Nullable<decimal> p_TRH { get; set; }
        public Nullable<decimal> p_TRL { get; set; }
        public Nullable<decimal> p_TehP_righ { get; set; }
        public Nullable<decimal> p_TehP_left { get; set; }
        public string Agregat { get; set; }
    }
}
