//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAVO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class l2l3interactionEntities : DbContext
    {
        public l2l3interactionEntities()
            : base("name=l2l3interactionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DiagramToRollAVO> DiagramToRollAVO { get; set; }
    
        public virtual ObjectResult<sp_WebP_LoadAVO3Parametrs_Result> sp_WebP_LoadAVO3Parametrs(Nullable<System.DateTime> startDT, Nullable<System.DateTime> finishDT)
        {
            var startDTParameter = startDT.HasValue ?
                new ObjectParameter("StartDT", startDT) :
                new ObjectParameter("StartDT", typeof(System.DateTime));
    
            var finishDTParameter = finishDT.HasValue ?
                new ObjectParameter("FinishDT", finishDT) :
                new ObjectParameter("FinishDT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebP_LoadAVO3Parametrs_Result>("sp_WebP_LoadAVO3Parametrs", startDTParameter, finishDTParameter);
        }
    
        public virtual ObjectResult<sp_WebP_LoadAVO4Parametrs_Result> sp_WebP_LoadAVO4Parametrs(Nullable<System.DateTime> startDT, Nullable<System.DateTime> finishDT)
        {
            var startDTParameter = startDT.HasValue ?
                new ObjectParameter("StartDT", startDT) :
                new ObjectParameter("StartDT", typeof(System.DateTime));
    
            var finishDTParameter = finishDT.HasValue ?
                new ObjectParameter("FinishDT", finishDT) :
                new ObjectParameter("FinishDT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebP_LoadAVO4Parametrs_Result>("sp_WebP_LoadAVO4Parametrs", startDTParameter, finishDTParameter);
        }
    
        public virtual ObjectResult<sp_WebP_LoadAVO5Parametrs_Result> sp_WebP_LoadAVO5Parametrs(Nullable<System.DateTime> startDT, Nullable<System.DateTime> finishDT)
        {
            var startDTParameter = startDT.HasValue ?
                new ObjectParameter("StartDT", startDT) :
                new ObjectParameter("StartDT", typeof(System.DateTime));
    
            var finishDTParameter = finishDT.HasValue ?
                new ObjectParameter("FinishDT", finishDT) :
                new ObjectParameter("FinishDT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebP_LoadAVO5Parametrs_Result>("sp_WebP_LoadAVO5Parametrs", startDTParameter, finishDTParameter);
        }
    
        public virtual ObjectResult<sp_WebP_LoadAVO3DTEventsOTM_Result1> sp_WebP_LoadAVO3DTEventsOTM(Nullable<System.DateTime> dTCreate, Nullable<System.DateTime> dTProd, Nullable<decimal> lengthOffSet, Nullable<decimal> lengthDefect)
        {
            var dTCreateParameter = dTCreate.HasValue ?
                new ObjectParameter("DTCreate", dTCreate) :
                new ObjectParameter("DTCreate", typeof(System.DateTime));
    
            var dTProdParameter = dTProd.HasValue ?
                new ObjectParameter("DTProd", dTProd) :
                new ObjectParameter("DTProd", typeof(System.DateTime));
    
            var lengthOffSetParameter = lengthOffSet.HasValue ?
                new ObjectParameter("LengthOffSet", lengthOffSet) :
                new ObjectParameter("LengthOffSet", typeof(decimal));
    
            var lengthDefectParameter = lengthDefect.HasValue ?
                new ObjectParameter("LengthDefect", lengthDefect) :
                new ObjectParameter("LengthDefect", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebP_LoadAVO3DTEventsOTM_Result1>("sp_WebP_LoadAVO3DTEventsOTM", dTCreateParameter, dTProdParameter, lengthOffSetParameter, lengthDefectParameter);
        }
    
        public virtual ObjectResult<sp_WebP_LoadAVO4DTEventsOTM_Result> sp_WebP_LoadAVO4DTEventsOTM(Nullable<System.DateTime> dTCreate, Nullable<System.DateTime> dTProd, Nullable<decimal> lengthOffSet, Nullable<decimal> lengthDefect)
        {
            var dTCreateParameter = dTCreate.HasValue ?
                new ObjectParameter("DTCreate", dTCreate) :
                new ObjectParameter("DTCreate", typeof(System.DateTime));
    
            var dTProdParameter = dTProd.HasValue ?
                new ObjectParameter("DTProd", dTProd) :
                new ObjectParameter("DTProd", typeof(System.DateTime));
    
            var lengthOffSetParameter = lengthOffSet.HasValue ?
                new ObjectParameter("LengthOffSet", lengthOffSet) :
                new ObjectParameter("LengthOffSet", typeof(decimal));
    
            var lengthDefectParameter = lengthDefect.HasValue ?
                new ObjectParameter("LengthDefect", lengthDefect) :
                new ObjectParameter("LengthDefect", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebP_LoadAVO4DTEventsOTM_Result>("sp_WebP_LoadAVO4DTEventsOTM", dTCreateParameter, dTProdParameter, lengthOffSetParameter, lengthDefectParameter);
        }
    
        public virtual ObjectResult<sp_WebP_LoadAVO5DTEventsOTM_Result> sp_WebP_LoadAVO5DTEventsOTM(Nullable<System.DateTime> dTCreate, Nullable<System.DateTime> dTProd, Nullable<decimal> lengthOffSet, Nullable<decimal> lengthDefect)
        {
            var dTCreateParameter = dTCreate.HasValue ?
                new ObjectParameter("DTCreate", dTCreate) :
                new ObjectParameter("DTCreate", typeof(System.DateTime));
    
            var dTProdParameter = dTProd.HasValue ?
                new ObjectParameter("DTProd", dTProd) :
                new ObjectParameter("DTProd", typeof(System.DateTime));
    
            var lengthOffSetParameter = lengthOffSet.HasValue ?
                new ObjectParameter("LengthOffSet", lengthOffSet) :
                new ObjectParameter("LengthOffSet", typeof(decimal));
    
            var lengthDefectParameter = lengthDefect.HasValue ?
                new ObjectParameter("LengthDefect", lengthDefect) :
                new ObjectParameter("LengthDefect", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebP_LoadAVO5DTEventsOTM_Result>("sp_WebP_LoadAVO5DTEventsOTM", dTCreateParameter, dTProdParameter, lengthOffSetParameter, lengthDefectParameter);
        }
    
        public virtual int sp_TransportDiagramsAVO3(string roll, string nStend, string nInStend, Nullable<System.DateTime> startDT, Nullable<System.DateTime> finishDT)
        {
            var rollParameter = roll != null ?
                new ObjectParameter("Roll", roll) :
                new ObjectParameter("Roll", typeof(string));
    
            var nStendParameter = nStend != null ?
                new ObjectParameter("NStend", nStend) :
                new ObjectParameter("NStend", typeof(string));
    
            var nInStendParameter = nInStend != null ?
                new ObjectParameter("NInStend", nInStend) :
                new ObjectParameter("NInStend", typeof(string));
    
            var startDTParameter = startDT.HasValue ?
                new ObjectParameter("StartDT", startDT) :
                new ObjectParameter("StartDT", typeof(System.DateTime));
    
            var finishDTParameter = finishDT.HasValue ?
                new ObjectParameter("FinishDT", finishDT) :
                new ObjectParameter("FinishDT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TransportDiagramsAVO3", rollParameter, nStendParameter, nInStendParameter, startDTParameter, finishDTParameter);
        }
    
        public virtual ObjectResult<sp_WebP_MulSKO_B800_FromStend_Result> sp_WebP_MulSKO_B800_FromStend(string stendNumber)
        {
            var stendNumberParameter = stendNumber != null ?
                new ObjectParameter("StendNumber", stendNumber) :
                new ObjectParameter("StendNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebP_MulSKO_B800_FromStend_Result>("sp_WebP_MulSKO_B800_FromStend", stendNumberParameter);
        }
    
        public virtual ObjectResult<sp_WebP_MulSKO_P1750_FromStend_Result> sp_WebP_MulSKO_P1750_FromStend(string stendNumber)
        {
            var stendNumberParameter = stendNumber != null ?
                new ObjectParameter("StendNumber", stendNumber) :
                new ObjectParameter("StendNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebP_MulSKO_P1750_FromStend_Result>("sp_WebP_MulSKO_P1750_FromStend", stendNumberParameter);
        }
    
        public virtual int sp_TransportDiagramsAVO4(string roll, string nStend, string nInStend, Nullable<System.DateTime> startDT, Nullable<System.DateTime> finishDT)
        {
            var rollParameter = roll != null ?
                new ObjectParameter("Roll", roll) :
                new ObjectParameter("Roll", typeof(string));
    
            var nStendParameter = nStend != null ?
                new ObjectParameter("NStend", nStend) :
                new ObjectParameter("NStend", typeof(string));
    
            var nInStendParameter = nInStend != null ?
                new ObjectParameter("NInStend", nInStend) :
                new ObjectParameter("NInStend", typeof(string));
    
            var startDTParameter = startDT.HasValue ?
                new ObjectParameter("StartDT", startDT) :
                new ObjectParameter("StartDT", typeof(System.DateTime));
    
            var finishDTParameter = finishDT.HasValue ?
                new ObjectParameter("FinishDT", finishDT) :
                new ObjectParameter("FinishDT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TransportDiagramsAVO4", rollParameter, nStendParameter, nInStendParameter, startDTParameter, finishDTParameter);
        }
    
        public virtual int sp_TransportDiagramsAVO5(string roll, string nStend, string nInStend, Nullable<System.DateTime> startDT, Nullable<System.DateTime> finishDT)
        {
            var rollParameter = roll != null ?
                new ObjectParameter("Roll", roll) :
                new ObjectParameter("Roll", typeof(string));
    
            var nStendParameter = nStend != null ?
                new ObjectParameter("NStend", nStend) :
                new ObjectParameter("NStend", typeof(string));
    
            var nInStendParameter = nInStend != null ?
                new ObjectParameter("NInStend", nInStend) :
                new ObjectParameter("NInStend", typeof(string));
    
            var startDTParameter = startDT.HasValue ?
                new ObjectParameter("StartDT", startDT) :
                new ObjectParameter("StartDT", typeof(System.DateTime));
    
            var finishDTParameter = finishDT.HasValue ?
                new ObjectParameter("FinishDT", finishDT) :
                new ObjectParameter("FinishDT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TransportDiagramsAVO5", rollParameter, nStendParameter, nInStendParameter, startDTParameter, finishDTParameter);
        }
    
        public virtual ObjectResult<sp_WebP_MulSKO_B800_FromRoll_Result> sp_WebP_MulSKO_B800_FromRoll(string rollNumber)
        {
            var rollNumberParameter = rollNumber != null ?
                new ObjectParameter("RollNumber", rollNumber) :
                new ObjectParameter("RollNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebP_MulSKO_B800_FromRoll_Result>("sp_WebP_MulSKO_B800_FromRoll", rollNumberParameter);
        }
    
        public virtual ObjectResult<sp_WebP_MulSKO_P1750_FromRoll_Result> sp_WebP_MulSKO_P1750_FromRoll(string rollNumber)
        {
            var rollNumberParameter = rollNumber != null ?
                new ObjectParameter("RollNumber", rollNumber) :
                new ObjectParameter("RollNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebP_MulSKO_P1750_FromRoll_Result>("sp_WebP_MulSKO_P1750_FromRoll", rollNumberParameter);
        }
    }
}
