//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAVO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sv_Web_TimeProduction
    {
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateProduction { get; set; }
        public string LocalId { get; set; }
        public string GlobalId { get; set; }
        public Nullable<decimal> Thickness { get; set; }
        public Nullable<decimal> Width { get; set; }
        public decimal Length { get; set; }
        public Nullable<decimal> Weight { get; set; }
    }
}
